export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  /**
   * 与 popular 数据相关的 actionType
   *
   */
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS'
};
