export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  /**
   * 与 popular 数据相关的 actionType
   *
   */
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  /**
   * 与 popular 上拉加载更多相关的 actionType
   *
   */
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL'
};
