export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  /**
   * 与 popular 数据相关的 actionType
   *
   */
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  /**
   * 与 popular 上拉加载更多相关的 actionType
   *
   */
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  /**
   * 与 trending 数据相关的 actionType
   *
   */
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  /**
   * 与 trending 上拉加载更多相关的 actionType
   *
   */
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',

  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',

  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE',
  FLUSH_TRENDING_FAVORITE: 'FLUSH_TRENDING_FAVORITE'


};
